language: node_js

node_js:
  - "node"

services:
  - mysql

before_install:
  - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test'; GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost'; FLUSH PRIVILEGES;"
  - mysql -u root < init.sql

after_success:
  - cat /tmp/mysql.err

after_failure:
  - cat /tmp/mysql.err
